import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://127.0.0.1:5173');
await page.getByRole('button',{name:'Enter the experiment'}).waitFor();
await fs.mkdir('evidence/ui',{recursive:true});
await page.screenshot({path:'evidence/ui/ready.png'});
await page.getByRole('button',{name:'Inspect circuit',exact:true}).click();
await page.getByRole('button',{name:'Silence looming inputs',exact:true}).click();
await page.waitForTimeout(3200);
if(!(await page.locator('#right-result').innerText()).includes('COLLISION'))throw Error('Intervention did not resolve collision');
if(!(await page.locator('#left-result').innerText()).includes('ESCAPED'))throw Error('Baseline did not escape');
await page.screenshot({path:'evidence/ui/intervention.png'});
await page.getByRole('button',{name:'Restore outputs',exact:true}).click();
await page.waitForTimeout(3200);
if(!(await page.locator('#right-result').innerText()).includes('ESCAPED'))throw Error('Restore did not restore original escape');
await page.getByRole('button',{name:'Back to duel',exact:true}).click();
await page.getByRole('button',{name:'Enter the experiment'}).click();
await page.waitForTimeout(1600);
await page.locator('#dodge').dispatchEvent('pointerdown',{pointerType:'mouse'});
await page.waitForTimeout(1000);
await page.setViewportSize({width:1280,height:800});
await page.screenshot({path:'evidence/ui/desktop.png'});
await page.setViewportSize({width:640,height:500});
await page.screenshot({path:'evidence/ui/compact.png'});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow');
await fs.writeFile('evidence/ui/browser-check.json',JSON.stringify({errors,intervention:'passed',restore:'passed',horizontalOverflow:false},null,2));
await browser.close();if(errors.length)throw Error(errors.join('\n'));console.log('Browser smoke checks passed');
