import './style.css';
import {WingSound} from './sound';
import {load,digest,latency,clearance,shuffled,clamp,type Catalog,type Pair,type Trace} from './core';
import {Arena,Anatomy} from './scene';
if(import.meta.env.PROD)void import('@vercel/analytics').then(({inject})=>inject());
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
$('#app').innerHTML=`<main class="shell">
 <header class="mast"><div class="brand"><div class="wordmark">FLINCH<span style="color:var(--cyan)">.</span></div><p>You vs. a simulated<br>fly brain</p></div><div class="mast-right"><span class="mode">Precomputed neural replay</span><button class="icon-button" id="presentation" aria-label="Toggle presentation mode" title="Presentation mode">⛶</button></div></header>
 <div class="stage-bar"><span><strong id="mode-label">ESCAPE DUEL</strong> <span id="stage-caption"> / CONNECTOME EXPERIMENT 01</span></span><div class="round-dots" aria-label="Round progress"><i></i><i></i><i></i><i></i></div></div>
 <section class="arena" aria-label="Side by side flight arenas"><div class="lanes"><section class="lane"><div class="lane-header"><div><div class="eyebrow" id="left-role">HUMAN CONTROL</div><h2 id="left-title">YOU</h2></div><span class="index">01</span></div><div class="lane-bottom"><div><div id="left-result" class="result-chip"></div><div class="metric" id="left-metric">— <small>ms elapsed</small></div></div><div class="hint" id="left-hint"><kbd>SPACE</kbd> to dodge<br>One move. Make it count.</div></div></section><section class="lane"><div class="lane-header"><div><div class="eyebrow" id="right-role">CONNECTOME CONTROL</div><h2 id="right-title">SIMULATED FLY</h2></div><span class="index">02</span></div><div class="lane-bottom"><div><div id="right-result" class="result-chip"></div><div class="metric" id="right-metric">— <small>ms simulated</small></div></div><div class="hint" id="right-hint">Neural escape readout<br>Same threat. Same dodge.</div></div></section></div>
 <div class="center-card" id="card"><div class="eyebrow" id="card-kicker">A SMALL BRAIN. A SPLIT SECOND.</div><h1 id="card-title">Would you dodge?</h1><p id="card-copy">An approaching object. Two identical flies.<br>Your reflexes against a connectome-based model.</p><div id="score" class="score hidden"></div><button id="start" class="primary" disabled>Loading real traces…</button><div class="loading-line" id="loading"><i></i></div><p class="mini" id="card-mini">4 rounds · 2 practice runs · Space or tap to dodge</p></div><div class="live-status hidden" id="live-status" aria-live="polite"></div></section>
 <section class="neural" aria-label="Neural evidence"><div class="anatomy" id="anatomy"><div class="anatomy-label"><div class="eyebrow">DATASET SOMA POSITIONS</div></div><span class="count" id="soma-count">Loading sourced anatomy</span></div><div class="circuit"><div class="circuit-top"><div class="eyebrow">INSIDE THE ESCAPE CIRCUIT</div><span class="circuit-state" id="circuit-state">Recorded population activity</span></div><div class="neural-flow"><div class="inputs"><div class="node" id="lc4"><b>LC4</b><small>Expansion</small></div><div class="node" id="lplc2"><b>LPLC2</b><small>Angular size</small></div></div><div class="flow-line" id="transmission"></div><div class="node" id="dnp"><b>DNp01</b><small>Escape readout</small></div><div class="flow-line"></div><div class="output" id="output">Assigned<br>dodge</div></div><canvas class="timeline" id="timeline" aria-label="Recorded LC4, LPLC2 and DNp01 spikes with simulation time cursor"></canvas><div class="timeline-labels"><span>VISUAL ONSET</span><span id="timeline-label">700 ms simulated</span></div></div></section>
 <div class="bottom"><div class="status" id="status">Preparing the experiment…</div><div class="actions"><div class="replay-controls hidden" id="replay-controls"><select id="trial-select" aria-label="Recorded threat"></select><select id="speed" aria-label="Replay speed"><option value="0.25">¼× slow motion</option><option value="1">1× real time</option></select><input id="seek" aria-label="Replay time" type="range" min="0" max="700" step="1" value="0"></div><button id="inspect" class="quiet" disabled>Inspect circuit</button><button id="intervene" class="danger hidden">Silence looming inputs</button><button id="next" class="primary hidden">Next round →</button><button id="dodge" class="primary hidden">Dodge <kbd>SPACE</kbd></button><button id="play-replay" class="hidden">Replay ↻</button></div></div>
 <footer class="footer"><span id="provenance">male-cns:v1.0 · Connectome-based simulation</span><span><button id="download">Save result</button> &nbsp; / &nbsp; <button id="methods">Methods & credits</button></span></footer>
 </main><dialog id="methods-dialog"><button class="close" id="close-methods" aria-label="Close methods">✕</button><h2>The model behind the move.</h2><p><strong>Built from a real fruit fly’s neural wiring.</strong> The simulated opponent uses a network derived from the publicly released male fruit-fly connectome: a map of real neurons and their connections produced by HHMI Janelia’s FlyEM team, Cambridge / MRC LMB and Google Research. A spiking simulation runs on that wiring, and its escape signal controls the fly’s assigned dodge through recorded traces. This is a connectome-based model, rather than a neural network trained to play this game.</p><p>Modeled visual input → connectome simulation → assigned dodge. Geometry drives LC4/LPLC2 feature channels and a retinotopic luminance input. The first DNp01 spike supplies an escape timestamp. The lateral dodge is a shared game rule, not a simulated fly body.</p><p><strong>Two different clocks.</strong> Human input is elapsed browser time from the first rendered stimulus frame. Model escape is simulated time from encoder onset. These are not calibrated measurements of a living fly, and a score tie remains a tie.</p><p><strong>Real traces, prepared in advance.</strong> The same threat, initial state and seed are replayed in both circuit conditions. Silencing blocks the outgoing transmission of 126 LC4 and 185 LPLC2 neurons; those cells can still spike. The timeline shows recorded population counts, not individual-neuron events. The static anatomical cloud uses all 141,781 available soma positions. Coordinates preserve dataset x/y/z axes, centered and uniformly scaled; the view is flipped vertically for display.</p><p>The bank responded to 20/20 hit courses and 20/20 near misses. This game therefore uses four validated hit courses only. Each session selects a recorded seed for each course. No classification or biological-necessity claim is made. Traces continue under the original undodged viewpoint; only the first escape is used, so this is not closed-loop flight.</p><p>Code: <a href="https://github.com/blendi-remade/fly-brain-minecraft" target="_blank" rel="noreferrer">Blendi Remade / fal.ai</a>, MIT, commit 6cfa301. Data: male-cns:v1.0, FlyEM (HHMI Janelia), Cambridge / MRC LMB and Google Research, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Derived graph retains connections ≥5 synapses, removes autapses, assigns transmitter signs and maps photoreceptors to columns. 176,422 neurons; 6,287,749 retained connections. FLINCH is independent of those institutions.</p><p id="performance">Frame timing is measured during play and included in result downloads.</p></dialog>`;
type State='loading'|'ready'|'armed'|'running'|'resolved'|'summary'|'replay';
type Result={pairId:string;seed:number;trialHash:string;humanMs:number|null;inputMethod:string|null;humanSurvived:boolean;modelSurvived:boolean;modelMs:number|null;practice:boolean;valid:boolean;reason?:string;maxFrameGapMs:number};
let catalog:Catalog,pair:Pair,arena:Arena,anatomy:Anatomy;
let state:State='loading',sessionSeed=crypto.getRandomValues(new Uint32Array(1))[0],order:Pair[]=[],round=0,practice=true,practiceRound=0,results:Result[]=[],human:number|null=null,inputMethod:string|null=null;
let held=false,armAt=0,onset=0,lastFrame=0,maxGap=0,runTime=-1,resolveAt=0,replayAt=0,replayT=0,replayPaused=false,intervention=false,returnState:State='ready',replayKind:'circuit'|'duel'='circuit';
const gaps:number[]=[];let lastUi=0;const horizon=()=>pair.trial.durationMs-pair.trial.onsetMs;
function say(text:string){$('#status').innerHTML=text}
function show(id:string,yes:boolean){$(id).classList.toggle('hidden',!yes)}
function banner(text:string){$('#live-status').textContent=text;show('#live-status',!!text)}
function metric(id:string,value:number|null,unit:string){$(id).innerHTML=`${value===null?'—':unit==='ms elapsed'?Math.round(value):value.toFixed(1)} <small>${unit}</small>`}
function outcome(id:string,success:boolean){$(id).textContent=success?'ESCAPED':'COLLISION';$(id).classList.toggle('hit',!success)}
function resetLabels(){ $('#left-title').textContent='YOU';$('#right-title').textContent='SIMULATED FLY';$('#left-role').textContent='HUMAN CONTROL';$('#right-role').textContent='CONNECTOME CONTROL';$('#left-hint').innerHTML='<kbd>SPACE</kbd> to dodge<br>One move. Make it count.';$('#right-hint').innerHTML='Neural escape readout<br>Same threat. Same dodge.';$('#transmission').classList.remove('cut');$('#left-result').textContent='';$('#right-result').textContent='';metric('#left-metric',null,'ms elapsed');metric('#right-metric',null,'ms simulated');}
function chooseOrder(){const ids=shuffled([...new Set(catalog.pairs.map(p=>p.id))],sessionSeed);order=ids.map((id,i)=>shuffled(catalog.pairs.filter(p=>p.id===id),sessionSeed+i)[0]);}
function arm(){if(continuous){$('#mode-label').textContent='CONTINUOUS';} (document.activeElement as HTMLElement)?.blur();state='armed';human=null;inputMethod=null;maxGap=0;runTime=-1;armAt=performance.now()+800+((sessionSeed+round*347+practiceRound*181)%801);resetLabels();show('#card',false);show('#next',false);show('#dodge',true);show('#replay-controls',false);show('#intervene',false);show('#play-replay',false);$('#inspect').setAttribute('disabled','');banner(held?'RELEASE SPACE':'GET READY');say(practice?`<strong>Practice ${practiceRound+1} / 2.</strong> Wait for the object, then press Space or tap Dodge.`:'Wait for the object. <strong>Space to dodge.</strong>');$('#stage-caption').textContent=practice?` / PRACTICE ${practiceRound+1} OF 2`:` / ROUND ${round+1} OF ${order.length}`;document.querySelectorAll('.round-dots i').forEach((e,i)=>{e.classList.toggle('active',!practice&&i===round);e.classList.toggle('done',!practice&&i<round)});}
function start(){if(state==='loading')return;continuous=false;$('#mode-label').textContent='ESCAPE DUEL';results=[];sessionSeed=crypto.getRandomValues(new Uint32Array(1))[0];chooseOrder();round=0;practice=true;practiceRound=0;pair=order[0];show('#score',false);arm();}
function snapshot(valid=true,reason?:string):Result{return {pairId:pair.id,seed:pair.seed,trialHash:pair.trialHash,humanMs:human,inputMethod,humanSurvived:clearance(pair.trial,human)>0,modelSurvived:clearance(pair.trial,latency(pair.normal))>0,modelMs:latency(pair.normal),practice,valid,reason,maxFrameGapMs:maxGap}}
function invalidate(reason:string){if(state!=='armed'&&state!=='running')return;results.push(snapshot(false,reason));state='resolved';show('#dodge',false);show('#next',true);$('#next').textContent='Retry this round →';$('#next').dataset.retry='true';banner('ROUND NOT SCORED');say(`${reason}. Your attempt is saved as invalid; retry when ready.`);}
function respond(method:string){if(state==='armed'){invalidate('False start — input before visual onset');return}if(state!=='running'||human!==null)return;human=performance.now()-onset;inputMethod=method;wingSound.dodge();metric('#left-metric',human,'ms elapsed');say('<strong>Response recorded.</strong> The opponent is revealed after this trial.');show('#dodge',false);}
function resolve(){state='resolved';resolveAt=performance.now();const r=snapshot();results.push(r);if(!r.humanSurvived||!r.modelSurvived)wingSound.collision();metric('#right-metric',r.modelMs,'ms simulated');outcome('#left-result',r.humanSurvived);outcome('#right-result',r.modelSurvived);banner(r.humanSurvived?'YOU ESCAPED':'TOO LATE');say(practice?'Practice complete. The model’s action is now available in replay.':`<strong>${r.humanSurvived?'Clean escape.':'Collision.'}</strong> Your browser time and the model’s simulated time are shown separately.`);show('#dodge',false);show('#next',true);$('#next').dataset.retry='false';$('#next').textContent=practice?(practiceRound===0?'Second practice →':'Begin duel →'):(round===order.length-1?'See results →':'Next round →');$('#inspect').removeAttribute('disabled');show('#play-replay',true);$('#play-replay').textContent='Replay this round ↻';if(continuous){show('#next',false);show('#play-replay',false);$('#inspect').setAttribute('disabled','');say('Next threat incoming. <strong>Space to dodge · Esc to finish.</strong>');}}
function next(){if(continuous){if($('#next').dataset.retry==='true'){arm();return}advanceContinuous();return}if($('#next').dataset.retry==='true'){arm();return}if(practice){if(practiceRound===0){practiceRound=1;pair=order[1];arm()}else{practice=false;pair=order[0];arm()}return}round++;if(round>=order.length){summary();return}pair=order[round];arm()}
function summary(){state='summary';show('#dodge',false);banner('');show('#next',false);show('#card',true);show('#score',true);const rs=results.filter(r=>r.valid&&!r.practice),h=rs.filter(r=>r.humanSurvived).length,m=rs.filter(r=>r.modelSurvived).length;$('#card-kicker').textContent='ESCAPE DUEL / COMPLETE';$('#card-title').textContent=h===m?'A shared escape.':h>m?'You made it out.':'The circuit was ready.';$('#card-copy').textContent='Escapes decide the score. The two clocks tell different stories.';$('#score').innerHTML=`<span>${h}<small style="font-size:14px;display:block">YOU</small></span><span>${m}<small style="font-size:14px;display:block">MODEL</small></span>`;$('#start').textContent='Play again';$('#card-mini').textContent='Now change the circuit. Replay the same threat.';say('<strong>What triggered its escape?</strong> Inspect a real trial, then silence the looming outputs.');$('#stage-caption').textContent=' / RESULTS';$('#inspect').removeAttribute('disabled');if(continuous){$('#mode-label').textContent='CONTINUOUS';$('#card-kicker').textContent='CONTINUOUS / SESSION COMPLETE';$('#card-title').textContent='Every escape counts.';$('#card-mini').textContent='Choose a mode below · Play again to start';}}
function inspect(){if(!catalog)return;returnState=state;state='replay';replayKind='circuit';intervention=false;const r=results.find(r=>r.valid&&!r.practice)||results.find(r=>r.valid);pair=r?catalog.pairs.find(p=>p.id===r.pairId&&p.seed===r.seed)!:order[0];$('#trial-select').innerHTML=(results.some(r=>r.valid)?results.filter(r=>r.valid):order.map(p=>({pairId:p.id,seed:p.seed,practice:false}))).map((r,i)=>`<option value="${r.pairId}/${r.seed}" ${r.pairId===pair.id&&r.seed===pair.seed?'selected':''}>${r.practice?'Practice':'Threat'} ${i+1} · ${r.pairId.slice(-2)}</option>`).join('');show('#trial-select',true);show('#card',false);show('#next',false);show('#dodge',false);show('#replay-controls',true);show('#intervene',true);show('#play-replay',true);$('#inspect').textContent='Back to duel';$('#intervene').textContent='Silence looming inputs';replayLabels();beginReplay();updateHash();}
function replayLabels(){resetLabels();$('#left-title').textContent='NORMAL CIRCUIT';$('#right-title').textContent=intervention?'OUTPUTS SILENCED':'NORMAL CIRCUIT';$('#left-role').textContent='RECORDED SIMULATION';$('#right-role').textContent=intervention?'LC4 + LPLC2 INTERVENTION':'MATCHED CONTROL';$('#left-hint').textContent='Same threat · same seed';$('#right-hint').textContent=intervention?'311 cells: transmission blocked':'Select “Silence looming inputs”';$('#transmission').classList.toggle('cut',intervention);$('#mode-label').textContent='CIRCUIT REPLAY';$('#stage-caption').textContent=' / SAME THREAT. DIFFERENT CIRCUIT.';say(intervention?'<strong>Sensory cells still spike. Their outputs are silenced.</strong> Observe the recorded escape readout.':'<strong>What triggered the escape?</strong> Replay the same threat, then change the circuit.');}
function beginReplay(){$('#left-result').textContent='';$('#right-result').textContent='';replayAt=performance.now();replayT=0;replayPaused=false;banner('');$('#play-replay').textContent='Pause Ⅱ';}
function updateHash(){if(replayKind==='circuit')history.replaceState(null,'',`#replay=${pair.id}/${pair.seed}/${intervention?1:0}`)}
function exitReplay(){history.replaceState(null,'',location.pathname);$('#mode-label').textContent='ESCAPE DUEL';$('#inspect').textContent='Inspect circuit';show('#replay-controls',false);show('#intervene',false);show('#play-replay',false);resetLabels();if(returnState==='summary')summary();else if(returnState==='ready'){state='ready';show('#card',true);banner('');say('Four validated threats. Your one job: get out of the way.')}else{state='resolved';pair=practice?order[practiceRound]:order[Math.min(round,order.length-1)];show('#next',true);banner('TRIAL COMPLETE');say('Continue when you’re ready.')}}
function duelReplay(){returnState=state;state='replay';replayKind='duel';show('#card',false);show('#next',false);show('#replay-controls',true);show('#trial-select',false);show('#play-replay',true);$('#inspect').textContent='Back to duel';say('Exact presentation replay. Input is disabled; the result is unchanged.');beginReplay();}
$('#start').onclick=()=>selectedMode==='continuous'?startContinuous():start();$('#next').onclick=next;$('#dodge').onpointerdown=e=>{e.preventDefault();respond(e.pointerType||'pointer')};$('#inspect').onclick=()=>state==='replay'?exitReplay():inspect();
$('#intervene').onclick=()=>{intervention=!intervention;$('#intervene').textContent=intervention?'Restore outputs':'Silence looming inputs';replayLabels();beginReplay();updateHash()};
$('#play-replay').onclick=()=>{if(state!=='replay'){duelReplay();return}if(replayT>=horizon()){beginReplay();return}replayPaused=!replayPaused;$('#play-replay').textContent=replayPaused?'Play ▶':'Pause Ⅱ'};
$('#trial-select').onchange=()=>{const [id,seed]=$<HTMLSelectElement>('#trial-select').value.split('/');pair=catalog.pairs.find(p=>p.id===id&&p.seed===+seed)!;beginReplay();updateHash()};
$('#seek').oninput=()=>{replayT=+$<HTMLInputElement>('#seek').value;replayPaused=true;$('#play-replay').textContent='Play ▶'};
$('#presentation').onclick=()=>{document.body.classList.toggle('presentation');if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.();};
$('#methods').onclick=()=>{if(state==='running'||state==='armed')invalidate('Methods opened during the response window');$<HTMLDialogElement>('#methods-dialog').showModal()};$('#close-methods').onclick=()=>$<HTMLDialogElement>('#methods-dialog').close();
$('#download').onclick=()=>{const payload={version:1,sessionSeed,mode:continuous?'Continuous':'Escape Duel',execution:'Precomputed neural replay',results,parameters:catalog?.parameters,replay:state==='replay'?{pairId:pair.id,seed:pair.seed,intervention,timeMs:replayT}:null,frameTiming:{samples:gaps.length,medianMs:percentile(.5),p95Ms:percentile(.95)}};const u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`flinch-${sessionSeed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
document.addEventListener('keydown',e=>{if(e.code!=='Space'||(e.target as HTMLElement).matches('select,input,textarea')||((e.target as HTMLElement).matches('button')&&state!=='armed'&&state!=='running')||$<HTMLDialogElement>('#methods-dialog').open)return;e.preventDefault();if(e.repeat||held)return;held=true;respond('keyboard')});document.addEventListener('keyup',e=>{if(e.code==='Space'){held=false;if(state==='armed'){armAt=performance.now()+1000;banner('GET READY')}}});
window.addEventListener('blur',()=>{held=false;if((state==='running'&&human===null)||state==='armed')invalidate('Window focus lost')});document.addEventListener('visibilitychange',()=>{if(document.hidden&&((state==='running'&&human===null)||state==='armed'))invalidate('Tab hidden')});
function percentile(p:number){if(!gaps.length)return null;return +[...gaps].sort((a,b)=>a-b)[Math.min(gaps.length-1,Math.floor(gaps.length*p))].toFixed(2)}
function timeline(trace:Trace,t:number,reveal:boolean){const canvas=$<HTMLCanvasElement>('#timeline'),r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr)}const ctx=canvas.getContext('2d')!;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);for(let i=0;i<3;i++){ctx.strokeStyle='#233242';ctx.beginPath();ctx.moveTo(0,10+i*16);ctx.lineTo(r.width,10+i*16);ctx.stroke()}for(const id of ['#lc4','#lplc2','#dnp'])$(id).classList.remove('active');if(!reveal){$('#circuit-state').textContent='Activity revealed after your decision';return}const populations=['LC4','LPLC2','DNp01'];for(const e of trace.populationEvents){const time=e.tMs-trace.inputOnsetSimMs;if(time<0||time>t)continue;const i=populations.indexOf(e.population);ctx.fillStyle=i===2?'#ffc578':'#66deff88';const height=Math.min(12,Math.log2(e.spikes+1)*1.5);ctx.fillRect(time/horizon()*r.width,10+i*16-height,1.5,height);if(t-time<35&&e.spikes)$(['#lc4','#lplc2','#dnp'][i]).classList.add('active')}
 const escape=latency(trace);if(escape!==null&&t>=escape){ctx.strokeStyle='#ffc578';ctx.setLineDash([2,3]);ctx.beginPath();ctx.moveTo(escape/horizon()*r.width,0);ctx.lineTo(escape/horizon()*r.width,r.height);ctx.stroke();ctx.setLineDash([])}ctx.strokeStyle='#e8eff5';ctx.beginPath();ctx.moveTo(t/horizon()*r.width,0);ctx.lineTo(t/horizon()*r.width,r.height);ctx.stroke();$('#circuit-state').textContent=`${Math.round(t)} ms · ${intervention&&state==='replay'?'Silenced outputs':'Recorded populations'}`;
}
function frame(now:number){requestAnimationFrame(frame);const dt=lastFrame?now-lastFrame:0;lastFrame=now;if(!arena||!pair)return;continuousTick(now);wingSound.update((['armed','running','resolved'].includes(state)||(state==='replay'&&!replayPaused))&&!$<HTMLDialogElement>('#methods-dialog').open);
 if(state==='armed'&&now>=armAt&&!held){state='running';onset=performance.now();runTime=0;maxGap=0;banner('');}
 else if(state==='running'){runTime=now-onset;maxGap=Math.max(maxGap,dt);gaps.push(dt);if(gaps.length>4000)gaps.shift();if(dt>50&&human===null){invalidate('Frame gap exceeded 50 ms');return}if(runTime>=horizon())resolve();}
 let t=state==='running'?runTime:state==='resolved'||state==='summary'?horizon():-1;let actions:(number|null)[]=[human,latency(pair.normal)];let reveal=state==='resolved'||state==='summary'||state==='replay';let visible=state==='running'||reveal;let trace=pair.normal;
 if(state==='replay'){if(!replayPaused)replayT=Math.min(horizon(),replayT+dt*Number($<HTMLSelectElement>('#speed').value));t=replayT;if(replayT>=horizon()){$('#play-replay').textContent='Replay ↻';replayPaused=true}if(replayKind==='circuit'){trace=intervention?pair.silenced:pair.normal;actions=[latency(pair.normal),latency(trace)];}else{const r=[...results].reverse().find(r=>r.valid&&r.pairId===pair.id&&r.seed===pair.seed);actions=[r?.humanMs??null,latency(pair.normal)];}metric('#left-metric',actions[0]!==null&&t>=actions[0]! ?actions[0]:null,replayKind==='duel'?'ms elapsed':'ms simulated');metric('#right-metric',actions[1]!==null&&t>=actions[1]! ?actions[1]:null,'ms simulated');$<HTMLInputElement>('#seek').value=String(t);}
 const collisions=actions.map(a=>clearance(pair.trial,a)<=0);if(state==='running')actions=[human,null];
 arena.draw(pair.trial,t,actions,visible,state==='running',reveal?collisions:[false,false],now,continuous&&state==='resolved'&&$('#next').dataset.retry!=='true'?clamp((now-resolveAt-600)/400):0);
 if(state==='replay'&&t>=horizon()){outcome('#left-result',!collisions[0]);outcome('#right-result',!collisions[1]);if(replayKind==='circuit'&&intervention)say(`<strong>${actions[1]===null?'No escape was recorded in the silenced circuit.':'The silenced circuit still produced an escape.'}</strong> Restore outputs to replay the original baseline.`)}
 if(now-lastUi>30){updateResultDots();timeline(trace,Math.max(0,t),reveal);lastUi=now}if(state==='resolved'&&now-resolveAt>600&&$('#live-status').textContent!=='ROUND NOT SCORED')banner('');
}
async function init(){try{catalog=await load(n=>{$('#loading i').style.width=`${Math.round(n*100)}%`;$('#start').textContent=`Checking traces · ${Math.round(n*100)}%`});chooseOrder();pair=order[0];arena=new Arena($('.arena'),Array.from(document.querySelectorAll<HTMLElement>('.lane')));const r=await fetch('/data/flinch/soma.bin');if(!r.ok)throw Error('Missing anatomical positions');const raw=await r.arrayBuffer();if(await digest(raw)!==catalog.soma.sha256)throw Error('Anatomy checksum mismatch');anatomy=new Anatomy($('#anatomy'),new Float32Array(raw));$('#soma-count').textContent=`${catalog.soma.count.toLocaleString()} positions · static anatomy`;$('#provenance').textContent=`male-cns:v1.0 · ${pair.normal.simulatedNeurons.toLocaleString()} simulated neurons`;state='ready';$('#start').removeAttribute('disabled');$('#start').textContent='Start playing';selectMode(selectedMode);show('#loading',false);$('#inspect').removeAttribute('disabled');say('Choose a mode, then <strong>Start playing.</strong>');requestAnimationFrame(frame);const hash=decodeURIComponent(location.hash).match(/^#replay=(course-\d+)\/(\d+)\/([01])$/);if(hash){const p=catalog.pairs.find(p=>p.id===hash[1]&&p.seed===+hash[2]);if(p){inspect();pair=p;intervention=hash[3]==='1';$('#intervene').textContent=intervention?'Restore outputs':'Silence looming inputs';$<HTMLSelectElement>('#trial-select').innerHTML=`<option value="${p.id}/${p.seed}">${p.id} · ${p.seed}</option>`;replayLabels();beginReplay();updateHash()}}setInterval(()=>{$('#performance').textContent=`Presentation frame timing: median ${percentile(.5)??'—'} ms; p95 ${percentile(.95)??'—'} ms from ${gaps.length} measured frames. Gaps over 50 ms before a response invalidate that attempt.`},3000)}catch(e){$('#card-title').textContent='Evidence unavailable';$('#card-copy').textContent=String(e);$('#start').textContent='Reload to retry';$('#start').removeAttribute('disabled');$('#start').onclick=()=>location.reload();say('The duel is blocked until its real neural traces and anatomy pass integrity checks.');console.error(e)}}
let continuous=false;
let selectedMode:'continuous'|'classic'='continuous';
const continuousButton=document.createElement('button');continuousButton.id='continuous';continuousButton.textContent='Continuous mode';continuousButton.disabled=true;
const modeControls=document.createElement('div');modeControls.className='mode-controls';modeControls.setAttribute('role','group');modeControls.setAttribute('aria-label','Play mode');
const classicButton=document.createElement('button');classicButton.id='classic';classicButton.textContent='Classic duel';classicButton.disabled=true;
modeControls.append(continuousButton,classicButton);$('.bottom').prepend(modeControls);
const finishButton=document.createElement('button');finishButton.id='finish-run';finishButton.textContent='Finish run · Esc';finishButton.className='hidden';$('.actions').prepend(finishButton);
$('.actions').append($('#inspect'));
function selectMode(mode:'continuous'|'classic'){
 selectedMode=mode;
 if(state==='ready'){
  $('#mode-label').textContent=mode==='continuous'?'CONTINUOUS':'ESCAPE DUEL';
  $('#card-mini').textContent=mode==='continuous'?'Space or tap to dodge · Automatic next threats':'2 practice runs · 4 scored rounds · Space or tap to dodge';
 }
}
continuousButton.onclick=()=>selectMode('continuous');classicButton.onclick=()=>selectMode('classic');finishButton.onclick=finishContinuous;
const streakDisplay=document.createElement('span');streakDisplay.id='streaks';streakDisplay.className='continuous-streaks hidden';$('.stage-bar').append(streakDisplay);
const continuousNote=document.createElement('p');
continuousNote.textContent='Continuous mode automatically chains independent trials at the original speed, resetting the scene and neural trace for each threat. Collisions reset your streak; play continues. Space or Dodge escapes, Esc or Finish run ends the session. This mode does not simulate a continuously adapting brain.';
$('#performance').before(continuousNote);
function startContinuous(){
 if(!catalog||!arena)return;
 history.replaceState(null,'',location.pathname);$('#inspect').textContent='Inspect circuit';
 start();continuous=true;practice=false;order=shuffled(catalog.pairs,sessionSeed);pair=order[0];arm();
 $('#card-kicker').textContent='CONTINUOUS MODE';
}
function advanceContinuous(){
 round++;if(round>=order.length)order.push(...shuffled(catalog.pairs,sessionSeed+round));
 pair=order[round];arm();
}
function finishContinuous(){
 if(state==='running'||state==='armed')results.push(snapshot(false,'Session ended before trial completion'));
 summary();
}
function continuousTick(now:number){
 if(state==='ready')selectMode(selectedMode);
 const playing=['armed','running','resolved'].includes(state);
 continuousButton.disabled=classicButton.disabled=!arena||playing||state==='replay';
 continuousButton.setAttribute('aria-pressed',String(selectedMode==='continuous'));
 classicButton.setAttribute('aria-pressed',String(selectedMode==='classic'));
 const active=continuous&&['armed','running','resolved'].includes(state);
 show('#finish-run',active);
 show('#streaks',continuous&&state!=='replay');
 if(continuous){
  const rs=results.filter(r=>r.valid&&!r.practice);
  const streak=(key:'humanSurvived'|'modelSurvived')=>{let n=0;for(let i=rs.length-1;i>=0&&rs[i][key];i--)n++;return n};
  streakDisplay.textContent=`STREAK  YOU ${streak('humanSurvived')} · MODEL ${streak('modelSurvived')}`;
  if(active)$('#stage-caption').textContent=` / THREAT ${round+1} · SPACE TO DODGE`;
  if(state==='resolved'&&$('#next').dataset.retry!=='true'&&now-resolveAt>=1100&&!document.hidden&&!$<HTMLDialogElement>('#methods-dialog').open)advanceContinuous();
 }
}
document.addEventListener('keydown',e=>{
 if(!continuous||e.repeat||$<HTMLDialogElement>('#methods-dialog').open||(e.target as HTMLElement).matches('select,input,textarea'))return;
 if(e.code==='Escape'&&['armed','running','resolved'].includes(state)){e.preventDefault();finishContinuous();}
 else if(e.code==='Enter'&&state==='resolved'&&$('#next').dataset.retry==='true'){e.preventDefault();arm();}
 else if(e.code==='Enter'&&state==='summary'){e.preventDefault();selectedMode==='continuous'?startContinuous():start();}
});
let resultDotsKey='';
for(const side of ['left','right']){
 const dots=document.createElement('div');dots.id=side+'-round-results';dots.className='round-results';dots.setAttribute('role','group');
 $('#'+side+'-title').after(dots);
}
function updateResultDots(){
 const inPractice=practice&&state!=='ready'&&state!=='loading';
 const hidden=state==='replay'&&replayKind==='circuit';
 const completed=results.filter(r=>r.valid&&r.practice===inPractice);
 const count=continuous?Math.min(8,Math.max(4,completed.length+1)):inPractice?2:4;
 const offset=continuous?Math.max(0,completed.length-8):0;
 const key=JSON.stringify([hidden,inPractice,continuous,completed.map(r=>[r.humanSurvived,r.modelSurvived])]);
 if(key===resultDotsKey)return;resultDotsKey=key;
 for(const side of ['left','right']){
  const host=$('#'+side+'-round-results');host.classList.toggle('hidden',hidden);
  host.setAttribute('aria-label',`${side==='left'?'Your':'Model'} ${inPractice?'practice':'round'} results`);
  host.innerHTML=Array.from({length:count},(_,i)=>{
   const r=completed[i+offset],win=r&&(side==='left'?r.humanSurvived:r.modelSurvived);
   const label=`${inPractice?'Practice':'Round'} ${i+offset+1}: ${r?(win?'escaped':'collision'):'not yet scored'}`;
   return `<span class="round-result ${r?(win?'escaped':'collision'):'pending'}" role="img" aria-label="${label}" title="${label}"></span>`;
  }).join('');
 }
}
const wingSound=new WingSound();
const soundIcon=(enabled:boolean)=>enabled?`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="M15.5 8.5a5 5 0 0 1 0 7"/><path d="M18.5 5.5a9 9 0 0 1 0 13"/></svg>`:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="m16 9 5 5m0-5-5 5"/></svg>`;
const soundButton=document.createElement('button');soundButton.id='sound';soundButton.className='sound-toggle';
function renderSoundButton(){soundButton.innerHTML=`${soundIcon(wingSound.enabled)}<span>Sound ${wingSound.enabled?'on':'off'}</span>`;soundButton.setAttribute('aria-label',wingSound.enabled?'Turn sound off':'Turn sound on');soundButton.setAttribute('aria-pressed',String(wingSound.enabled));}
renderSoundButton();
$('.mast-right').prepend(soundButton);
soundButton.onclick=()=>{wingSound.enabled=!wingSound.enabled;renderSoundButton();if(wingSound.enabled)wingSound.test();else wingSound.update(false)};
document.addEventListener('pointerdown',()=>wingSound.unlock());
document.addEventListener('keydown',()=>wingSound.unlock());
document.addEventListener('visibilitychange',()=>{if(document.hidden)wingSound.update(false)});
updateResultDots();
init();
